# Changes here will be overwritten by Copier
_commit: v1.8.3
_src_path: .\copier-aistack\
author_email: philipptemminghoff@googlemail.com
author_fullname: AIStack
author_username: aistack
copyright_date: '2025'
copyright_holder: AIStack
copyright_holder_email: philipptemminghoff@googlemail.com
libraries_use_pydantic: true
libraries_use_qt: false
project_description: Abstractions & Tools for OCR / document processing
project_name: Docler
python_minimum_version: '3.12'
python_package_command_line_name: docler
python_package_distribution_name: docler
python_package_import_name: docler
repository_name: docler
repository_namespace: aistack
repository_provider: github.com

